### ISSUE TITLE
Implement new subject area design

### ISSUE THREAD

**Issue by teeceeas** [ministryofjustice/find-moj-data#1243]
As a FMD user,
I want the subject areas to be clearly categorised, visually distinct, and intuitive to navigate,
so that I can quickly find and explore datasets relevant to my work with minimal confusion.

**Acceptance Criteria**
Implement as designed

**Comment by teeceeas** [comment]
Blocked by 1051 & 1226

**Comment by joe-horton-moj** [comment]
Design – @sdurnberger to review descriptions.

![Image](https://github.com/user-attachments/assets/3387109c-5916-4347-9a44-1da3f722c79e)

**Comment by MatMoore** [comment]
This is the component used for the 1 column grid on GOV.UK https://components.publishing.service.gov.uk/component-guide/cards

CSS: https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/stylesheets/govuk_publishing_components/components/_cards.scss

The whole row should be clickable

Seems like the little arrow is a block rotated 45 degrees rather than an icon

```css
  &::before {
    $dimension: 7px;
    $width: 3px;

    border-right: $width solid $govuk-brand-colour;
    border-top: $width solid $govuk-brand-colour;
    content: "";
    display: block;
    height: $dimension;
    position: absolute;
    right: govuk-spacing(1);
    top: 50%;
    margin-top: 5px;
    @include prefixed-transform($rotate: 45deg);
    width: $dimension;
  }
```
