### ISSUE TITLE
🐛 Tracker for datahub prefix search issue

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/find-moj-data#1739]
### Describe the bug.

Datahub [issue](https://github.com/datahub-project/datahub/issues/13781) raise and ryan Holstein notified.

Prefix search configuration was applied as per the guidance, however container entities were not prioritised as expected.

```
- queryRegex: .*
              simpleQuery: true
              prefixMatchQuery: true
              exactMatchQuery: true
              functionScore:
                functions:
                  - filter:
                      prefix:
                        urn:
                          value: "urn:li:container:"
                    weight: 1000.0
                score_mode: multiply
                boost_mode: multiply
```

I have raised a issue on the datahub repo and there has been some feedback regarding potential causes.

### Root Cause
Based on the townhall discussion, this is a known issue in DataHub where:

Different Elasticsearch Indices: Each entity type (containers, datasets, etc.) is stored in separate Elasticsearch indices, which affects how scores are calculated and compared across entity types.

Field Matching Disparities: Datasets typically have more searchable fields (columns, descriptions, schemas, etc.) that can match query terms, naturally boosting their relevance scores compared to containers which have fewer matching fields.

Solution
The weight of 5 for containers is simply not high enough to overcome these scoring disparities. You need to significantly increase the container boost weight.

### Recommended Actions

Increase Container Weight by experimenting with much higher weights (i.e. 500). You may need to go even higher depending on your data.

Use explainSearchQuery API
Utilize DataHub's OpenAPI endpoint explainSearchQuery to:

Inspect actual document scores for containers vs datasets
Understand the scoring breakdown for your specific query "offence"
Fine-tune the weight based on the score differences you observe
Iterative Tuning Process

Start with a weight of 500
Run explainSearchQuery to compare container vs dataset scores
Adjust the weight up or down based on the score gap
Repeat until containers consistently appear at the top
