### ISSUE TITLE
Spike: how does DataHub only ingest opt-ins from CaDeT

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#340]
### User Story

This story is to determine how DataHub distinguishes the opted in items from CaDeT and ingests those but not the others

As a user of the create-a-derived-table service
I need to indicate that a derived table is suitable to be displayed in the catalogue
So that an automated process can ingest only those assets that have been flagged as useful

### Options

1. Change the create-a-derived-table pipelines so that the `manifest.json` is only compiled for a specific list of assets
2. Enforce a naming convention on create-a-derived-table so that the datahub ingestion can filter on regex patterns for assets
3. Ingest all tables from create-a-derived-table, then filter those tables based on custom metadata into find-moj-data

**Comment by murdo-moj** [comment]
https://docs.getdbt.com/reference/commands/cmd-docs
```dbt docs generate --select +orders```
>Use the --select argument to limit the nodes included within catalog.json. When this flag is provided, step (3) will be restricted to the selected nodes. All other nodes will be excluded. Step (2) is unaffected.

One option is to generate the DBT `catalog.json` for only the nodes which have the flag to ingest data to DataHub. This would have some complexity on the create-a-derived-table side, but would mean that no ingestion customisation would be needed into datahub.

**Comment by murdo-moj** [comment]
One option for `dbt` ingestion is to include a pattern in the naming of models which we want to ingest to DataHub, to be picked up by the node_name_pattern option

https://datahubproject.io/docs/generated/ingestion/sources/dbt/#config-details

node_name_pattern AllowDenyPattern | regex patterns for dbt model names to filter in ingestion.Default: {'allow': ['.*'], 'deny': [], 'ignoreCase': True}
-- | --

**Comment by murdo-moj** [comment]
[Datahub transformers](https://datahubproject.io/docs/metadata-ingestion/docs/transformer/intro/) allow customisation of metadata of ingested assets, but they do not support skipping the asset altogether.

**Comment by MatMoore** [comment]
## Option 1: Requesting a custom manifest from CaDeT team

### What needs to change?

CaDeT's deploy docs workflow currently does this

```yaml
      - name: Build docs and copy required files to temp folder
        run: |
          dbt docs generate --no-compile --target prod
          mkdir ../github_pages
          cp target/index.html ../github_pages
          cp target/catalog.json ../github_pages
          cp target/manifest.json ../github_pages
          cp target/graph.gpickle ../github_pages

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: github_pages

      - name: Export run artefacts to S3
        # Copy files from local directory to S3
        if: ${{ always() }}
        run: python ../scripts/export_run_artefacts.py
```

This would need to be added/amended to push custom manifest/catalog jsons to s3.

## Who owns what?
We would be responsible for:
- any guidance on what dbt command to run
- writing the Datahub ingestion recipe and pointing it at the place where the manifest/catalog files live

The team that owns CaDeT would be responsible for:
- the workflow that runs the command and publishes the manifest/catalog files
- deciding what metadata should be included/excluded

Currently the bucket is owned by the AP and Datahub has a role that can read from it. We could also invert this so that we manage our own bucket (or API) and create a role for AP to publish.

This might not be an issue right away but as the number of ingestions grows I'd expect it to become harder to manage within the team, so generally we should aim to delegate responsibility to the teams that know about the data.

**Comment by MatMoore** [comment]
## What needs filtering?

### catalogue.json
> This file contains information from your [data warehouse](https://docs.getdbt.com/terms/data-warehouse) about the tables and [views](https://docs.getdbt.com/terms/view) produced and defined by the resources in your project.

This can be filtered using the `--select, --exclude, --selector` options to the doc command as mentioned above - but it seems like this will not prevent intermediate models from being ingested - since Datahub will still pick those up from the manifest(?) TBC

### manfiest.json
> This single file contains a full representation of your dbt project's resources (models, tests, macros, etc), including all node configurations and resource properties. **Even if you're only running some models or tests, all resources will appear in the manifest (unless they are disabled)** with most of their properties. (A few node properties, such as compiled_sql, only appear for executed nodes.)

**Comment by MatMoore** [comment]
Note: running `dbt docs generate` on CaDeT might rely on having run `dbt run` first - so I'm going to try this out on a cut down version of the project for simplicity.

If the filtering option does not work, the next option to test is generating a full manifest, but including tags on the ones we actually want to show up in the frontend. Datahub will ingest everything, but we will be able to filter out any "internal to CaDeT" stuff.

**Comment by MatMoore** [comment]
Yep, option 1 doesn't work. Everything that was filtered out still gets picked up via the manifest.json. 

Conclusion: rather than trying to filter at the DBT end, we should enforce tags that we can filter on in our frontend.

**Comment by MatMoore** [comment]
## Option 2: Opt-in via meta (recommended)

CaDeT owners opt-in via including something like `catalogue_audience: moj` in the model's [meta block](https://docs.getdbt.com/reference/resource-configs/meta)

For example:

```yaml
---
version: 2
models:
  - name: common_platform_derived__cases_fct
    meta:
      catalogue_audience: moj
```

Our DBT ingestion recipe needs to include the following:

```yaml
        meta_mapping:
          catalogue_audience:
            match: moj
            operation: "add_tag"
            config:
              tag: "show_to_all_moj"
```

This creates a tag `dbt:show_to_all_moj` (the prefix is controlled by the `tag_prefix` option)
