### ISSUE TITLE
X to remove search

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#459]
> could the search have an 'x' to clear action button when active and not empty? just like on gov.uk search?
> 
> 
> 
> ![Image](https://github.com/ministryofjustice/find-moj-data/assets/115145706/91a43466-bfb0-4de5-843d-f6c2c6e81477)
> 
>  

 _Originally posted by @alex-vonfeldmann in [#423](https://github.com/ministryofjustice/find-moj-data/issues/423#issuecomment-2163310598)_

**Comment by YvanMOJdigital** [comment]
keyboard shortcut?

**Comment by jemnery** [comment]
Also add to glossary search. Should this reset the page to all glossary terms? 🤔

**Comment by MatMoore** [comment]
This behaviour actually comes from `type="search"`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search#differences_between_search_and_text_types

It's then customised on GOV.UK with

```css
&::-webkit-search-cancel-button {
    -webkit-appearance: none;
    background-image: url("govuk_publishing_components/icon-close.svg");
    background-position: center;
    background-repeat: no-repeat;
    cursor: pointer;
    height: 20px;
    margin-left: 0;
    margin-right: 0;
    width: 20px;
  }
}
```

We have icon-close-cross-black in the MOJ design system, so we could use that.
