### ISSUE TITLE
🐛 Data owner not displayed in FMD

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#556]
Data owner details are being populated at ingestion, but those are not being displayed in the front end.

**Comment by LavMatt** [comment]
It might be that the datahub documentation for ownership types is out of date. This isn't the cause of the issue but something to note.
> add_owner - Requires owner_type property in config which can be either user or group. Optionally accepts the owner_category config property which can be set to either a [custom ownership type](https://datahubproject.io/docs/ownership/ownership-types) urn like urn:li:ownershipType:architect or one of ['TECHNICAL_OWNER', 'BUSINESS_OWNER', 'DATA_STEWARD', 'DATAOWNER' (defaults to DATAOWNER).

The default ownership type `DATAOWNER` (as per the guidance) which is what our recipe is set to for named contacts for cadet doesn't seem to register as a type of owner in datahub rather being class as other and a custom ownership type.


![Image](https://github.com/user-attachments/assets/6faa457f-8474-48ae-9d2c-57e52f0ea463)



I have tested the below in the cadet ingestion recipe yaml and business owner is recognised as an ownership type in datahub
```
    meta_mapping:
      dc_owner:
        match: '.*'
        operation: 'add_owner'
        config:
          owner_type: user
          owner_category: BUSINESS_OWNER
```
see


![Image](https://github.com/user-attachments/assets/986ea559-ff3f-4105-9b19-1329f01867e9)
